import type { Metadata } from "next";
import { orbitron, SF_Pro } from "@/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				suppressHydrationWarning
				className={`${orbitron.variable} ${SF_Pro.variable} ${SF_Pro.className} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
